### ISSUE TITLE
View context config is never used

### ISSUE THREAD

**Issue by AMHOL** [dry-rb/dry-web-roda#77]
The auto-generated app configures a `context` for the dry-view base class, however, this never gets used as the roda view plugin just calls `roda_app['view.context']`, resolving from the container directly. The only way around this is to resolve the view in the plugin and get the context from the classes config, which feels very hacky.

https://github.com/dry-rb/dry-web-roda/blob/master/lib/roda/plugins/dry_view.rb#L10

**Comment by alejandrobabio** [comment]
@AMHOL If you are talking about [this](https://github.com/dry-rb/dry-web-roda/blob/master/lib/dry/web/roda/templates/subapp/view__controller.rb.tt#L13) line, I agree with you. It's not needed at all.

**Comment by AMHOL** [comment]
@alejandrobabio yep, that's the line that I mean, thanks for linking and clarifying.

**Comment by timriley** [comment]
Thanks for bringing this up, @AMHOL and @alejandrobabio.

For a certain kind of usage (solely rendering views via  `r.view` in the routes), you're right, you might think having a default context is not necessary.

However, if you had some views that you wanted to render directly, outside of HTTP routing, the default context object _is_ used and would allow these views to have the same access to the non-HTTP aspects of a standard view environment (e.g. if you had an "assets" object exposed in there).

Example via console:

```ruby
view = TestViewContext::Main::Container["views.welcome"]
# => #<TestViewContext::Main::Views::Welcome config=#<#<Class:0x00007ffbabe320c0>:0x00007ffbac97b5a8 @config={:paths=>[#<Pathname:/Users/tim/Scratch/test_view_context/apps/main/web/templates>], :layout=>"application", :template=>"welcome", :default_format=>:html, :context=>#<TestViewContext::Main::View::Context:0x00007ffbabe30338 @attrs={}>, :decorator=>#<Dry::View::Decorator:0x00007ffbabe32fc0>}>>

view.class.config.context
# => #<TestViewContext::Main::View::Context:0x00007ffbabe30338 @attrs={}>

TestViewContext::Main::Container["view.context"]
# => #<TestViewContext::Main::View::Context:0x00007ffbabe95cd8 @attrs={}>

view.()
# => "<html><body><h1>Welcome to dry-web-roda!</h1></body></html>"
```

Does that help explain things better?

After hearing this do you still think there's anything in this arrangement you might like to see changed?

**Comment by AMHOL** [comment]
I think there are a few possibilities, maybe a comment in the generated file explaining that context won't be used  when calling the view from the Roda roting tree, or updating the plugin to something like:

```ruby
class Roda
  module RodaPlugins
    module View
      def self.load_dependencies(app)
        app.plugin :flow
      end

      module InstanceMethods
        def view_context(view)
          if view.respond_to?(:get_context)
            view.get_context(view_context_options)
          else
            self.class["view.context"].with(view_context_options)
          end
        end

        def view_context_options
          {}
        end

        def view_key(action)
          "views.#{action}"
        end
      end

      module RequestMethods
        def view(name, options = {})
          view_key = scope.view_key(name)
          view = roda_class.resolve(view_key)
          view_context = scope.view_context(view)
          options = { context: view_context }.merge(options)

          is to: view_key, call_with: [options]
        end
      end
    end

    register_plugin :view, View
  end
end
```

And:

```ruby
module MyApp
  class View < Dry::View::Controller
    configure do |config|
      config.paths = [Container.root.join("web/templates")]
      config.context = Container["view.context"]
      config.layout = "application"
    end

    def get_context(view_context_options)
      config.context.with(view_context_options)
    end
  end
end
```

To ensure that the configured context is used.

**Comment by timriley** [comment]
@AMHOL perhaps you could build it into dry-view as `Dry::View::Controller#default_context` and then make the dry_view plugin changes like you outlined above? I'd be happy to see that go in :)

**Comment by alejandrobabio** [comment]
I'd like to see some working use case to figure out how to use it in a dry-web-roda app. 

I need to make some time window to investigate, but I did some debugging and the default config context seems to be an empty instance of the view context (because container returns an instance created without arguments). So, with this default context, it will be needed to call with some arguments `view.(context: my_context)`. Makes sense? 

I guess I'm missing something. After review, I'll bring some fresh data.

**Comment by alejandrobabio** [comment]
The issue here is that the container is frozen before load the Roda app, and the `view.context` is registered in the container before froze it. So, the `view.context  config.context` can't have any of the cool stuff defined in the app (e.g: csrf_token) because the Roda app does not exist at the moment of view context config setting.

This debug should clarify this:

```ruby
From: /home/alejandro/source/osp/dwr-todo-example/apps/main/system/boot.rb @ line 6 :

    1: # frozen_string_literal: true
    2: 
    3: require_relative 'todo/main/container'
    4: 
    5: binding.pry
 => 6: Todo::Main::Container.finalize!
    7: binding.pry
    8: 
    9: require 'todo/main/web'

~/source/osp/dwr-todo-example (main) > c

From: /home/alejandro/source/osp/dwr-todo-example/apps/main/lib/todo/main/view/controller.rb @ line 16 :

    11:     module View
    12:       class Controller < Dry::View::Controller
    13:         configure do |config|
    14:           config.paths = [Container.root.join('web/templates')]
    15:           binding.pry
 => 16:           config.context = Container['view.context']
    17:           config.layout = 'application'
    18:         end
    19:       end
    20:     end
    21:   end

~/source/osp/dwr-todo-example (Todo::Main...Controller) > n

From: /home/alejandro/source/osp/dwr-todo-example/apps/main/lib/todo/main/view/controller.rb @ line 17 :

    12:       class Controller < Dry::View::Controller
    13:         configure do |config|
    14:           config.paths = [Container.root.join('web/templates')]
    15:           binding.pry
    16:           config.context = Container['view.context']
 => 17:           config.layout = 'application'
    18:         end
    19:       end
    20:     end
    21:   end
    22: end

~/source/osp/dwr-todo-example (Todo::Main...Controller) > config.context
#<Todo::Main::View::Context:0x00000006819830 @attrs={}>
~/source/osp/dwr-todo-example (Todo::Main...Controller) > c

From: /home/alejandro/source/osp/dwr-todo-example/apps/main/system/boot.rb @ line 9 :

    4: 
    5: binding.pry
    6: Todo::Main::Container.finalize!
    7: binding.pry
    8: 
 => 9: require 'todo/main/web'

~/source/osp/dwr-todo-example (main) > 
```

**Comment by timriley** [comment]
@alejandrobabio Yep, everything you say is right.

It comes down to this: request-specific information is only available within each request, and not when the app is still booting up and yet to serve any requests. This is why we allow the view context to be provided when each view controller is called, and why our `r.view` Roda helper does this by default.

However, the default "empty" context object that is available when the app boots _may still be useful_ even without request-specific information. It comes down to what behaviour you choose to give it as the application author. Like I mentioned above, this default context object would still be useful for rendering views outside of the web request/response cycle, like for emails.

Since this issue was about the view context object "never being used", an since I've demonstrated why it's there and how it still may be used, I'm going to close this now.

@AMHOL I'd still love to see the changes you proposed if you'd like to make them to dry-view and dry-web-roda's dry_view plugin :)

**Comment by waiting-for-dev** [comment]
I think this issue should be reopened, maybe updating the title. The current behavior is breaking the principle of least surprise and it is also limiting in a way the full potential of `dry-view`.

I'll try to explain it. Right now when you look at the generated application code everything you see make you think that the configured context is actually used (the `configure` line, the `r.view` call, the generated view controller class...). However, when you try to change it for another one you see it is not the case. You try to run in the console the isolated view and you see that there the context is indeed used, so at last you end up in the `roda` plugin source code to realize why.

It is also limiting in a way the potential of `dry-view`. I you create a child context inheriting from the auto-generated one and you configure a view to use it, the HTTP request simply keeps using the parent one, because it is what is being resolved by `roda` plugin.

The workaround I use right now is something like

```ruby
r.view "static.home", context: self.class.container["views.static.home_context"].with(view_context_options)
```

which, of course, it is not very elegant.

Furthermore, I think that the use case where you can find this problem can be very common. If I'm not missing something, the only way to expose something to the layout from the view is through the context, so if you need to expose something that changes with the view the most sensible way is through context inheritance. For example, for a HTML `<title>` tag:

```erb
<title><%= "#{view_specific} | My Site" %>
```

Do you still think it is desirable to have @AMHOL proposal integrated? If so, @AMHOL , if you don't have the time I wouldn't mind to do it myself.

**Comment by AMHOL** [comment]
@waiting-for-dev that would be great if @timriley is still keen on the idea, thanks.

**Comment by waiting-for-dev** [comment]
Just to have all the information here, the use case I talked about can be solved with other solutions, like commented in this post:

https://discourse.dry-rb.org/t/dry-view-expose-to-layout/654

But, anyway, I still think it is needed.

Thanks @AMHOL ! :smile:

**Comment by timriley** [comment]
A couple of thoughts on this:

- If you don't want to keep the default context, you can remove [that line](https://github.com/dry-rb/dry-web-roda/blob/1ea22b01e4dfddab5535402d56af68de43c5f1f7/lib/dry/web/roda/templates/subapp/view__controller.rb.tt#L13) after you've generated the application.
- If you want to customise the view context class use on a per-request basis, then you can implement `#view_context` inside your app's `Dry::Web::Roda::Application` subclass and the `r.view` helper will pick it up.

The dry-view integration offered by dry-web-roda is very lightweight. You should definitely feel free to build your own inside your applications, with this as a starting point or otherwise.

I feel like having to have a dedicated subclasses for every view controller's context object is indicative of a design issue in dry-view itself, and I'd rather we think about addressing it there than papering it over with adjustments to the dry-view/roda integration here just yet.

Does that seem fair?

**Comment by waiting-for-dev** [comment]
> If you don't want to keep the default context, you can remove that line after you've generated the application.

The thing is that dry-web-roda roda plugin is providing the `context:` option when calling to `r.view`:

https://github.com/dry-rb/dry-web-roda/blob/master/lib/roda/plugins/dry_view.rb#L24

So, even if you remove that line, the same context is used. You have to override providing your own `context:` option, which gets merged with preference.

> I feel like having to have a dedicated subclasses for every view controller's context object is indicative of a design issue in dry-view itself, and I'd rather we think about addressing it there than papering it over with adjustments to the dry-view/roda integration here just yet.
>
> Does that seem fair?

Agree. First thing should be revisiting these parts :smile:
